### ISSUE TITLE
Add gprofiler results for tidy verse lesson to Rproject

### ISSUE THREAD

**Issue by marypiper** [hbctraining/Intro-to-R-flipped#13]
Let's add the tidy verse lesson to IntroR and link out to the modules instead of vice versa. We need to add the data to the project for IntroR and they should download the project containing the data on the landing page for the modules.

**Comment by rkhetani** [comment]
- Updated https://github.com/hbctraining/Intro-to-R-flipped/blob/master/lessons/01_introR-R-and-RStudio.md#adding-files-to-your-working-directory section to have them download the functional analysis results.
- Moved over Tidyverse lesson from Training modules to this repo and made some changes to the text to reflect the updates.
- Updated all the schedules to have the correct tidyverse lesson links.
