### ISSUE TITLE
New in-class activity about function

### ISSUE THREAD

**Issue by jihe-liu** [hbctraining/Intro-to-R-flipped#20]
Instead of creating two functions for temperature (https://hbctraining.github.io/Intro-to-R-flipped/activities/Day2_activities.html), could we just create one, to convert temperature of 32 in Fahrenheit to corresponding temperature in Kelvin? It adds a bit complexity for the function, and reduces redundancy.

**Comment by jihe-liu** [comment]
Add another exercise related to nesting function.

**Comment by rkhetani** [comment]
All set @Gammerdinger
