### ISSUE TITLE
Update teaching team in "reordering datasets" lesson

### ISSUE THREAD

**Issue by epartan** [hbctraining/Intro-to-R-flipped#31]
https://github.com/hbctraining/Intro-to-R-flipped/blob/master/lessons/09_reordering-to-match-datasets.md

Teaching team listed as
teaching_team <- c("Jihe", "Mary", "Meeta", "Radhika", "Will", "Emma")

Should update code and figure to match current team

**Comment by Gammerdinger** [comment]
Updated on the main page and the mkdocs page
